### ISSUE TITLE
Device Descriptor Request Failed

### ISSUE THREAD

**Issue by GiovanniANVitale** [ALSchwalm/pISO#51]
on plug in of piso to Windows 10 Device, error in device manager states: A request for the USB device descriptor failed.

**Comment by ALSchwalm** [comment]
I'm sorry you're having trouble. Does the pISO appear to be booting up correctly? Can you verify that this problem happens with other machines as well?

**Comment by GiovanniANVitale** [comment]
Booting up appears fine, menu structure is intact and  able to create virtual drives etc, but the device doesn't get detected by the local computer as being valid. I've tried two windows 10 devices so far, I'd suspected the usual Pi to Windows 10 connectivity problems with drivers etc, but nothing has worked so far. I'm going to build a Windows 7 machine in the morning to test against to see if the behaviour changes between Operating systems, or if the issue follows the pISO.

**Comment by GiovanniANVitale** [comment]
Tried with Windows 7, alternate SD card and PI, but still not recognized by the hardware as a valid USB device. 
Could this be a hardware fault?

**Comment by ALSchwalm** [comment]
It certainly seems like this could be a hardware issue. In order to confirm that, could connect your pISO to the computer with microUSB cable? This way, the raspberry pi will be handling all of the USB communications, so I would expect the issue to not occur. If the problem only happens with using the usb plug on the pISO, then it is likely a hardware fault.

**Comment by GiovanniANVitale** [comment]
Looks like both pi were the problem, ordered another zero w, and it works like a charm. Thanks for the help. Closing.
